// Login
export const LOGIN = {
    USERNAME: "LOGIN_USERNAME",
    PASSWORD: "LOGIN_PASSWORD",
    REMEMBER: "LOGIN_REMEMBER",
    SUBMIT:   "LOGIN_SUBMIT"
};

// Register
export const REGISTER = {
    USERNAME: "REGISTER_USERNAME",
    PASSWORD: "REGISTER_PASSWORD",
    FULLNAME: "REGISTER_FULLNAME",
    SUBMIT: "REGISTER_SUBMIT"
};
