// Login
export const LOGIN_USERNAME = "LOGIN_USERNAME";
export const LOGIN_PASSWORD = "LOGIN_PASSWORD";
export const LOGIN_REMEMBER = "LOGIN_REMEMBER";
export const LOGIN_SUBMIT = "LOGIN_SUBMIT";

// Register
export const REGISTER_USERNAME = "REGISTER_USERNAME";
export const REGISTER_DISPLAYNAME = "REGISTER_DISPLAYNAME";
export const REGISTER_SUBMIT = "REGISTER_SUBMIT";
